server {
    listen 80; # Nginx escuchará en el puerto 80 dentro del contenedor
    server_name localhost;
    root /var/www/html/public; # La raíz de tu aplicación Laravel (la carpeta 'public')

    # Encabezados de seguridad recomendados
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    # Intenta servir el archivo directamente, si no, reescribe a index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Procesa archivos PHP usando PHP-FPM
    location ~ \.php$ {
        fastcgi_pass php:9000; # 'php' es el nombre del servicio PHP en docker-compose
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Bloquea el acceso a archivos ocultos (ej. .env, .git)
    location ~ /\.(?!well-known).* {
        deny all;
    }
}